### ISSUE TITLE
wasm-pack use of fetch causes ExperimentalWarning on node <= 18

### ISSUE THREAD

**Issue by olizilla** [web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash#17]
When importing fr32 in a cli, it triggers the fetch warning in node 18, which makes the cli much less fun to use.

```
❯ node --trace-warnings ./cli.js
(node:65482) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:227:11)
    at fetch (node:internal/process/pre_execution:215:5)
    at fetch (file:///Users/oli/Code/web3-storage/pieces/node_modules/fr32-sha2-256-trunc254-padded-binary-tree-multihash/gen/wasm.js:257:21)
    at __wbg_init (file:///Users/oli/Code/web3-storage/pieces/node_modules/fr32-sha2-256-trunc254-padded-binary-tree-multihash/gen/wasm.js:224:17)
    at file:///Users/oli/Code/web3-storage/pieces/node_modules/fr32-sha2-256-trunc254-padded-binary-tree-multihash/src/lib.js:5:7
```

see: https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/blob/3acb44a333b6ca52a1c62aa8ce3fef824423117e/gen/wasm.js#L257

**Comment by Gozala** [comment]
I think could be fixed by returning an ArrayBuffer with those bytes instead, this is how rust generated glue code uses return of this function

https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/blob/f88a0dc88c89fc96133086ad24b01f4ae756f7d1/gen/wasm.js#L142-L158

P.S. I end up with fetch because prior version used to load the wasm file, but I had to base64 inline it because that was breaking bundlers 😭
